#!/bin/bash
###$1-old root VG name
###$2-host name


CONF=etc
OLDSLES=mnt
LOG=set_configuration.log
COMMAND=systemctl
OPSPACKAGE=./opsware-agent-60.0.71639.1-linux-SLES-12-X86_64

##set mountpoint from old sles11 server
mount /dev/$1/root /$OLDSLES/
mount /dev/$1/opt /$OLDSLES/opt/
mount /dev/$1/tmp /$OLDSLES/tmp/
mount /dev/$1/home /$OLDSLES/usr2/local/

######apx agent install task######

cd  /opt/apxpccp/
tar -xvf  /opt/apxpccp/apxpccp_lin64_create_pks_after_move.tar 
/opt/apxpccc/./recreate_pccp_pks_after_move.sh
/opt/apxpccp/apxcntl restart

####install DP agent####
rpm -Uvh /mnt/tmp/backup/omni_packages/*.rpm

####post checkes######

/root/scripts/migration/./post_migration_checks



for ora in $(cat ora_meintanace);do  ssh root@$ora "hostname; vgs ";done > ora_vg

while read p; do scp /usr2/local/dimitrge/migration/after_boot.sh      root@$p:/root/scripts; done < /infra/linux/SUSE-Manager/sap_list
while read p; do scp /usr2/local/dimitrge/migration/sles11to12     root@$p:/root/scripts; done < /infra/linux/SUSE-Manager/sap_list
while read p; do scp /usr2/local/dimitrge/migration/HPOA_12.06_Linux_64_v1.tar.gz      root@$p:/tmp ; done < /infra/linux/SUSE-Manager/sap_list
while read p; do scp -r /usr2/local/dimitrge/migration/backup      root@$p:/tmp ; done < /infra/linux/SUSE-Manager/sap_list
