#!/bin/bash
#################
###created by me###
#################

for p in [a-c]
do

    echo cfq > /sys/block/sd$p/queue/scheduler
    echo 1 > /sys/block/sd$p/queue/iosched/back_seek_penalty
    echo 10000 > /sys/block/sd$p/queue/iosched/fifo_expire_async
    echo 20 > /sys/block/sd$p/queue/iosched/fifo_expire_sync
    echo 1 > /sys/block/sd$p/queue/iosched/low_latency
    echo 6 > /sys/block/sd$p/queue/iosched/quantum
    echo 2 > /sys/block/sd$p/queue/iosched/slice_async
    echo 10 > /sys/block/sd$p/queue/iosched/slice_async_rq
    echo 1 > /sys/block/sd$p/queue/iosched/slice_idle
    echo 20 > /sys/block/sd$p/queue/iosched/slice_sync
done

echo 15 > /proc/sys/vm/swappiness
echo 10 > /proc/sys/vm/vfs_cache_pressure
echo 99 > /proc/sys/vm/dirty_ratio
echo 50 > /proc/sys/vm/dirty_background_ratio
echo 360000 > /proc/sys/vm/dirty_expire_centisecs
echo 360000 > /proc/sys/vm/dirty_writeback_centisecs
